### ISSUE TITLE
Maybe a bug adding very long URIs?

### ISSUE THREAD

**Issue by olea** [cygri/prefix.cc#28]
Hi:

I tried to add a new vocabulary at http://prefix.cc/, particularly at http://prefix.cc/iaph. Seems the application truncates the [URI](http://www.juntadeandalucia.es/datosabiertos/portal/iaph/dataset/dataset/6c199ca2-8d2e-4c12-833c-f28233a5251d/resource/38731571-42af-4373-b425-6dae73bacf79/download/tesauro-iaph.rdf#), which is particularly long.

I think I added it correctly but now it's wrong and seems I can't try to fix until tomorrow.

Thanks.

**Comment by cygri** [comment]
There is a maximum of 100 characters for the URI. Submissions that exceed the maximum should be refused with an error.

Currently the length of the URI is not checked, and URIs that are too long are simply truncated (due to the [DB schema definition](https://github.com/cygri/prefix.cc/blob/master/db_schema/schema.sql#L48)). That is a bug.

It would also be possible to increase the limit, but this is the first complaint about the limit I'm getting since prefix.cc started operations almost ten years ago. So I'm leaning towards the view that this namespace is unusual and outside of what's considered good practice by the community.

**Comment by olea** [comment]
I see. I'm not the owner of the resource so I can't provide a better main URI.

I've just created a PURL redirection: http://purl.org/iaph 

I guess I should wait until tomorrow to add it at prefix.cc, right?

**Comment by cygri** [comment]
You need to wait until tomorrow unless you can get online with a different IP address (to circumvent the IP check) and use a different browser (to circumvent the cookie check). The checks are intended to prevent spam and flooding. They are not meant to prevent correction of errors. It’s just difficult to distinguish those cases in a simple way.

**Comment by olea** [comment]
Just added the correct URI for iaph to prefix.cc.

Thanks very much :-)

**Comment by cygri** [comment]
I've added a check to the site, and going forward it will reject long URIs with an error message that states the restriction.

Thanks for the report!
